# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Site Setup
title: "MENA Investment Hub"
tagline: "An archive of the 113 publicly available of 116 Egyptian bilateral investment treaties (BITs), featuring verified texts and source PDFs."
description: "An archive of the 113 publicly available of 116 Egyptian bilateral investment treaties (BITs), featuring verified texts and source PDFs."
url: "https://menainvestmenthub.com" # custom domain
baseurl: "" # no subdirectory

# Author
author:
  name: Aya Hamza
  url: https://github.com/ayahamza1

# Pagination
paginate: 5

# Optional Custom Vars
version: 2.1.0

# GitHub Repo
github:
  repo: https://github.com/ayahamza1/MENABITs

# Plugins (used by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-paginate
